add task3/task4
ShulgaVadim/OnlineStore pull request #1
Opened 2021-02-25 15:18 UTC by ShulgaVadim

2021-03-01 14:19 UTC, artemmoroz requested changes
Also, take a look at the project structure, some of the classes should be in domain module, some at console app and so on. parent module is redundant.

2021-03-01 14:19 UTC, artemmoroz commented on store/src/main/java/DOMxmlReader.java
> +    public Map<String, String> XMLreader(String path) {
func name (camel case)

2021-03-01 14:19 UTC, artemmoroz commented on store/src/main/java/Product.java
> +@Builder
what for builder here?

2021-03-01 14:19 UTC, artemmoroz commented on store/src/main/java/ProductPriceComparator.java
> +        if (o1.getPrice() > o2.getPrice())
you can use Double.compare instead

2021-03-01 14:19 UTC, artemmoroz commented on store/src/main/java/ProductRatingComparator.java
> +        if (o1.getRate() > o2.getRate())
the same as above

2021-03-01 14:19 UTC, artemmoroz commented on store/src/main/java/RandomStorePopulator.java
> +    public ArrayList<Product> populateTheStore() {
functions should return as minimal possible class/interface, so, here u should use List<Product>

2021-03-01 14:19 UTC, artemmoroz commented on store/src/main/java/RandomStorePopulator.java
> +        Faker faker = new Faker();
u can init faker instance only once for populator instance or even once for all populator instances

2021-03-01 14:19 UTC, artemmoroz commented on store/src/main/java/RandomStorePopulator.java
> +        ArrayList<Product> products = new ArrayList<>();
the same as at line #8

2021-03-01 14:19 UTC, artemmoroz commented on store/src/main/java/Store.java
> +    ArrayList<Product> products;
List

2021-03-01 14:19 UTC, artemmoroz commented on store/src/main/java/Store.java
> +    public void printProducts(ArrayList<Product> products) {
what for u place products as input param here?

2021-03-01 14:19 UTC, artemmoroz commented on store/src/main/java/Store.java
> +        for (int i = 0; i < products.size(); i++) {
in this case u can use simplified 'for' syntax ( for(Product p: products)

2021-03-01 14:19 UTC, artemmoroz commented on store/src/main/java/RandomStorePopulator.java
> +            Category myCategory = null;
so, all this code is not what was required. The task is to read all Category class implementations in some package, and create their instances and populate some products to them

2021-03-01 14:19 UTC, artemmoroz commented on store/src/main/java/Store.java
> +    public ArrayList<Product> sortByNameAsc() {
please think about all *sort* methods, how they could be rafcatored

2021-03-01 14:19 UTC, artemmoroz commented on store/src/main/java/Store.java
> +    public void showTopProductsByPriceDesc(int n) {
please read aboud SOLID principle, and split this method in several, and method that get smthing from user (Scanner) should not be in store class

2021-03-01 14:19 UTC, artemmoroz commented on store/src/main/java/Store.java
> +            for (int i = 0; i < n; i++) {
take a look at java stream api and select proper method from it.

2021-03-01 14:19 UTC, artemmoroz commented on store/src/main/java/StoreApp.java
> +        String path = System.getProperty("user.dir") + "/store/src/main/resources/sort.xml";
you path are incorrect, cause / is only windows path seporator

2021-03-01 14:19 UTC, artemmoroz commented on store/src/main/java/StoreApp.java
> +        ArrayList<Product> sortedProducts = evroOpt.sortProduct(sortCondition, "price");
according to the task, sorting should be done according to the whole config file, not just one item. So, create a solution that supports multiple comporators.

2021-03-02 08:24 UTC, ShulgaVadim commented on store/src/main/java/DOMxmlReader.java
> +    public Map<String, String> XMLreader(String path) {
changed.

2021-03-02 08:37 UTC, ShulgaVadim commented on store/src/main/java/ProductPriceComparator.java
> +        if (o1.getPrice() > o2.getPrice())
changed.

2021-03-02 08:37 UTC, ShulgaVadim commented on store/src/main/java/ProductRatingComparator.java
> +        if (o1.getRate() > o2.getRate())
changed.

2021-03-02 08:44 UTC, ShulgaVadim commented on store/src/main/java/RandomStorePopulator.java
> +    public ArrayList<Product> populateTheStore() {
changed.

2021-03-02 08:48 UTC, ShulgaVadim commented on store/src/main/java/RandomStorePopulator.java
> +        ArrayList<Product> products = new ArrayList<>();
changed

2021-03-02 08:49 UTC, ShulgaVadim commented on store/src/main/java/Store.java
> +    public void printProducts(ArrayList<Product> products) {
changed

2021-03-02 08:50 UTC, ShulgaVadim commented on store/src/main/java/Store.java
> +    ArrayList<Product> products;
changed

2021-03-02 08:55 UTC, ShulgaVadim commented on store/src/main/java/Store.java
> +        for (int i = 0; i < products.size(); i++) {
changed

2021-03-02 12:26 UTC, ShulgaVadim commented on store/src/main/java/Store.java
> +    public void printProducts(ArrayList<Product> products) {
changed.

2021-03-03 11:10 UTC, ShulgaVadim commented on store/src/main/java/RandomStorePopulator.java
> +        Faker faker = new Faker();
changed.

2021-03-05 11:02 UTC, artemmoroz requested changes

2021-03-05 11:02 UTC, artemmoroz commented on consoleApp/pom.xml
> +            <groupId>groupId</groupId>
invalid name, read about the artifact naming

2021-03-05 11:02 UTC, artemmoroz commented on consoleApp/src/main/java/Command.java
> +        List<Product> products = store.products;
you should use getters and setters, to follow incapsulation principle

2021-03-05 11:02 UTC, artemmoroz commented on consoleApp/src/main/java/Command.java
> +        topProducts = products.stream().sorted(productPriceComparatorDesc).limit(5).collect(Collectors.toList());
it is  not an error, but it is better to parameterize such functions, and set the number of products as income param

2021-03-05 11:02 UTC, artemmoroz commented on consoleApp/src/main/java/Command.java
> +        topProducts.forEach(System.out::println);
you can print products in the above stream

2021-03-05 11:02 UTC, artemmoroz commented on consoleApp/src/main/java/Command.java
> +        if (command.equals("top")) {
i think there should be sort command also, cause you need to handle : simple print products, sorted, top and quit

2021-03-05 11:02 UTC, artemmoroz commented on consoleApp/src/main/java/StoreApp.java
> +        Map<String, String> sortCondition = reader.XmlReader(resource.getPath());
XmlReader - func name, camel case!

2021-03-05 11:02 UTC, artemmoroz commented on domain/src/main/java/categories/Fruit.java
> +        setName(FRUIT_CATEGORY);
super constructor is preferable

2021-03-05 11:02 UTC, artemmoroz commented on store/src/main/java/RandomStorePopulator.java
> +    Reflections reflections = new Reflections("categories");
wrong package name

2021-03-05 11:02 UTC, artemmoroz commented on store/src/main/java/RandomStorePopulator.java
> +            namesOfCategory.add(subClassesForCategory.stream().collect(Collectors.toList())
very strange method, and a lot of cpu overhead, you read category list multiple times.

2021-03-05 11:02 UTC, artemmoroz commented on store/src/main/java/RandomStorePopulator.java
> +            int randomInt = (int) (Math.random() * subClassesForCategory.size());
please, think one more time about this method impl. it is very complex and overengineered.

2021-03-05 11:02 UTC, artemmoroz commented on store/src/main/java/Store.java
> +    public List<Product>multipleSort(Map<String, String> map){
a lot of duplicated code, and multiple sort still not supported.

2021-03-05 11:02 UTC, artemmoroz commented on store/src/main/java/utility/DomXmlReader.java
> +    public Map<String, String> XmlReader(String path) {
https://www.oracle.com/java/technologies/javase/codeconventions-namingconventions.html  - CAMEL CASE

2021-03-25 13:22 UTC, merged

2021-03-25 13:23 UTC, artemmoroz commented
everything is fine